DNA-500 Repositories example throws NoSuchMethodError due to conflicting log4j versions
This issue has been an occasional source of frustration for some time.  But I just noticed that we're quite a few releases behind on the SLF4J library (the latest is 1.5.6, but we're using 1.4.3).  According to http://www.slf4j.org/news.html this TRACE issue appears when using Log4J versions older than 1.2.12 (as demonstrated above), and this was reported and fixed as Bug 68 (http://bugzilla.slf4j.org/show_bug.cgi?id=68) in SLF4J 1.5.1 by having the Log4J adapter class remap TRACE messages as DEBUG messages.

Simply upgrading the SLF4J API and adapter versions to 1.5.1 (or higher) should therefore fix this problem (hopefully once and for all).  Changing the SLF4J API and Log4J adapter to 1.5.6 (the latest) appears to have worked with no regressions, and I was able to successfully run the repositories example using run.sh from target/dna-example-repositories-basic.dir/.

git-svn-id: https://svn.jboss.org/repos/modeshape/trunk@1143 76366958-4244-0410-ad5e-bbfabb93f86b