DNA-500 Repositories example throws NoSuchMethodError due to conflicting log4j versions
I just uploaded 1.5.8 to the JBoss Maven 2 repository (including source), and have changed our POM files to reference this version.  A complete build was successful, and the repository example was run successfully.

git-svn-id: https://svn.jboss.org/repos/modeshape/trunk@1146 76366958-4244-0410-ad5e-bbfabb93f86b